Repository vn-ki/anime-downloader, pull requests merged in 2020-07, with the labels that each got.

#437 Vidfree improvements
  anime_downloader/sites/animefree.py
Labels: enhancement

#440 even more fixes to animix
  anime_downloader/sites/animixplay.py
Labels: enhancement

#447 Added referer and window title to mpv
  anime_downloader/commands/dl.py
  anime_downloader/util.py
Labels: enhancement

#453 made animesimple less shit
  anime_downloader/config.py
  anime_downloader/sites/animesimple.py
Labels: enhancement

#455 Adds speed limit flag
  anime_downloader/commands/dl.py
  anime_downloader/config.py
  anime_downloader/session.py
  anime_downloader/util.py
Labels: enhancement, help wanted

#454 made sort_sources less prone to errors
  anime_downloader/sites/anime.py
Labels: help wanted

#434 Add HorribleSubs
  README.md
  anime_downloader/sites/horriblesubs.py
  anime_downloader/sites/init.py
Labels: help wanted, provider

#452 updated animerush to use sort_sources and made the code less shit
  anime_downloader/config.py
  anime_downloader/sites/animerush.py
Labels: don't merge

#457 Added provider 4anime.to
  README.md
  anime_downloader/sites/_4anime.py
  anime_downloader/sites/init.py
Labels: provider
